'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class BillingEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=BillingEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property impuesto() As DbSet(Of impuesto)
    Public Overridable Property categoria() As DbSet(Of categoria)
    Public Overridable Property tipoProducto() As DbSet(Of tipoProducto)
    Public Overridable Property unidadMedida() As DbSet(Of unidadMedida)
    Public Overridable Property unidadMedidaEquivalencia() As DbSet(Of unidadMedidaEquivalencia)
    Public Overridable Property producto() As DbSet(Of producto)

End Class
