'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class producto
    Public Property codProducto As String
    Public Property descripcion As String
    Public Property almacenMinimo As Nullable(Of Double)
    Public Property reorden As Nullable(Of Double)
    Public Property activo As Nullable(Of Boolean)
    Public Property codigoRapido As String
    Public Property codigoBarra As String
    Public Property notas As String
    Public Property rutaImagen As String
    Public Property idImpuesto As Integer
    Public Property idCategoria As Nullable(Of Integer)
    Public Property idTipoProducto As Nullable(Of Integer)

End Class
